### ISSUE TITLE
[win32 instantdex] Wrong bid/ask arrays

### ISSUE THREAD

**Issue by blackyblack** [jl777/libjl777#17]
numbids=1 and bids array is empty. numbids=2 and bids array contains 1 element. Probably 1 off error.

**Comment by jl777** [comment]
i think it is a timeshift. the arrays are created in a different thread and the display is for one version in the past. will investigate

**Comment by blackyblack** [comment]
win32 call:

BitcoinDarkd.exe SuperNET {\"plugin\":\"InstantDEX\",\"method\":\"orderbook\",\"baseid\":\"13851067422609193670\",\"relid\":\"5527630\",\"exchange\":\"nxtae\"}

should have 3 asks and 0 bids. But both bids and asks arrays are empty.

BitcoinDarkd.exe SuperNET {\"plugin\":\"InstantDEX\",\"method\":\"orderbook\",\"baseid\":\"7110939398145553585\",\"relid\":\"5527630\",\"exchange\":\"nxtae\"}

should have 5 bids and 17 asks. But both bids and asks arrays have 5 items.

**Comment by jl777** [comment]
this appears to be win specific, maybe due to it being based off of old version

**Comment by blackyblack** [comment]
Looks like fixed in the newer version.
