### ISSUE TITLE
[win32 instantdex] Wrong bid added to bids

### ISSUE THREAD

**Issue by blackyblack** [jl777/libjl777#18]
After placing a bid if failed with:

cant create accurate price ref.(100.000000 1.000000) -> (0.000000 0.000000)
error with incoming bidask

But it was added to orderbook.

**Comment by jl777** [comment]
plz post the exact API call that creates an error. there are two bugs here, not being able to create the accurate price and including bad value in the orderbook

**Comment by blackyblack** [comment]
"method":"placebid ","base":"5527630","rel":"3977863981551859762","price":100,"volume":1,"exchange":"InstantDEX"

I guess the price was broken due to failed getCurrency call.

**Comment by jl777** [comment]
3977863981551859762 is not a valid asset or currency, so the price should be zero. not sure this is a bug. I will add some error checking for invalid assetid
